### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by bcardarella** [beerlington/classy_enum-mongoid#1]
I guess this is a styling thing but what you can do for file organization:

```
lib/
  classy_enum-mongoid.rb
  classy_enum/
    mongoid.rb
    mongoid/
      <mongoid files>
      version.rb
```

Then `classy_enumy-enum.rb` just does:

``` ruby
require 'classy_enum/mongoid'
```

This is a convention that many projects that split into this plugin system are following.

**Comment by beerlington** [comment]
Thanks for the tip. I just went with the default structure that `bundle gem` gave me. Do you have an example of a project that uses this pattern? I was trying to find one, but couldn't think of any offhand.

**Comment by bcardarella** [comment]
All of my projects use it:
https://github.com/dockyard/client_side_validations-mongoid

And the Omniauth projects use a similar pattern:
https://github.com/intridea/omniauth-identity

There are bunch of others but I cannot recall offhand.

---

Brian Cardarella
Principal at DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard

On Fri, Aug 3, 2012 at 11:03 AM, Pete B
reply@reply.github.com
wrote:
